name: Validate Model Estimates

on:
  push:
    branches:
      - "assignment/did*"
      - "assignment/fes*"
      - "assignment/ivs*"
      - "assignment/rdd*"
      - "assignment/rct*"

jobs:
  # Differrences in Differences
  did:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'assignment/did')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Assert DID
        working-directory: assignments/did/code
        run: python test-did.py

  # Fixed Effects
  fes:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'assignment/fes')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Assert FEs
        working-directory: assignments/fes/code
        run: python test-fes.py

  # Instrumental Variables
  ivs:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'assignment/ivs')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Assert IVs
        working-directory: assignments/ivs/code
        run: python test-ivs.py

  # Regression Discontinuity Design
  rdd:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'assignment/rdd')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Assert RDD
        working-directory: assignments/rdd/code
        run: python test-rdd.py

  # [TEST WORKFLOW] Randomized Controlled Trial
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'assignment/rct')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Assert test module
        working-directory: assignments/rct/code
        run: python test-rct.py
